---
- name: "Testing"
  hosts: localhost
  connection: local
  gather_facts: true
  become: true

  vars:
    install_golang: "false"
    service_port: 8090
  roles:
  #- role: builder
  - role: roles/runner
